
# This file is automatically generated, you probably don't want to edit this

jmvtabregOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jmvtabregOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            outcome = NULL,
            predictors = NULL,
            tab_vars = NULL,
            wt = NULL,
            family = NULL,
            link = NULL,
            outcome_level = NULL,
            trials = NULL,
            effect = "auto",
            measure = "auto",
            empirical = TRUE,
            models = NULL,
            na = "drop_by_outcome",
            run_compare = FALSE,
            levels_order = NULL,
            levels_collapse = NULL,
            crosses = NULL,
            ref_levels = NULL,
            shape = NULL,
            multiplier = NULL,
            conf_level = 0.95,
            ci_method = "wald",
            stars = TRUE,
            color = "measure",
            color_signif = "grey_non_signif",
            display = "auto",
            n = "range",
            digits = "0",
            cleannames = TRUE,
            subtext = "",
            tab_theme = "light",
            wrap_rows = 35,
            wrap_cols = 15,
            export_format = "excel",
            exportExcel = FALSE,
            export_dir = "~/Documents",
            export_filename = "Reg_model",
            resetPath = FALSE,
            xl_check = FALSE,
            xl_replace = FALSE, ...) {

            super$initialize(
                package="tabxplor",
                name="jmvtabreg",
                requiresData=TRUE,
                ...)

            private$..outcome <- jmvcore::OptionVariables$new(
                "outcome",
                outcome,
                permitted=list(
                    "numeric",
                    "factor"),
                default=NULL)
            private$..predictors <- jmvcore::OptionVariables$new(
                "predictors",
                predictors,
                permitted=list(
                    "numeric",
                    "factor"),
                default=NULL)
            private$..tab_vars <- jmvcore::OptionVariable$new(
                "tab_vars",
                tab_vars,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..wt <- jmvcore::OptionVariable$new(
                "wt",
                wt,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..family <- jmvcore::OptionArray$new(
                "family",
                family,
                hidden=TRUE,
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "family",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionString$new(
                            "family",
                            NULL))))
            private$..link <- jmvcore::OptionArray$new(
                "link",
                link,
                hidden=TRUE,
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "link",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionString$new(
                            "link",
                            NULL))))
            private$..outcome_level <- jmvcore::OptionArray$new(
                "outcome_level",
                outcome_level,
                hidden=TRUE,
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "outcome_level",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionString$new(
                            "level",
                            NULL))))
            private$..trials <- jmvcore::OptionArray$new(
                "trials",
                trials,
                hidden=TRUE,
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "trials",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionString$new(
                            "n",
                            NULL))))
            private$..effect <- jmvcore::OptionList$new(
                "effect",
                effect,
                options=list(
                    "auto",
                    "conditional",
                    "marginal",
                    "at_reference"),
                default="auto")
            private$..measure <- jmvcore::OptionList$new(
                "measure",
                measure,
                options=list(
                    "auto",
                    "difference",
                    "ratio",
                    "odds_ratio",
                    "raw_coefficient"),
                default="auto")
            private$..empirical <- jmvcore::OptionBool$new(
                "empirical",
                empirical,
                default=TRUE)
            private$..models <- jmvcore::OptionArray$new(
                "models",
                models,
                hidden=TRUE,
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "models",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "label",
                            NULL),
                        jmvcore::OptionArray$new(
                            "vars",
                            NULL,
                            template=jmvcore::OptionVariable$new(
                                "vars",
                                NULL)),
                        jmvcore::OptionArray$new(
                            "crosses",
                            NULL,
                            template=jmvcore::OptionString$new(
                                "crosses",
                                NULL)))))
            private$..na <- jmvcore::OptionList$new(
                "na",
                na,
                options=list(
                    "drop_by_outcome",
                    "drop_by_model",
                    "drop_all",
                    "keep_for_predictors"),
                default="drop_by_outcome")
            private$..run_compare <- jmvcore::OptionAction$new(
                "run_compare",
                run_compare)
            private$..levels_order <- jmvcore::OptionArray$new(
                "levels_order",
                levels_order,
                hidden=TRUE,
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "levels_order",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionArray$new(
                            "levels",
                            NULL,
                            template=jmvcore::OptionString$new(
                                "levels",
                                NULL)))))
            private$..levels_collapse <- jmvcore::OptionArray$new(
                "levels_collapse",
                levels_collapse,
                hidden=TRUE,
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "levels_collapse",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionString$new(
                            "label",
                            NULL),
                        jmvcore::OptionArray$new(
                            "levels",
                            NULL,
                            template=jmvcore::OptionString$new(
                                "levels",
                                NULL)))))
            private$..crosses <- jmvcore::OptionArray$new(
                "crosses",
                crosses,
                hidden=TRUE,
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "crosses",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var1",
                            NULL),
                        jmvcore::OptionVariable$new(
                            "var2",
                            NULL))))
            private$..ref_levels <- jmvcore::OptionArray$new(
                "ref_levels",
                ref_levels,
                hidden=TRUE,
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "ref_levels",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionString$new(
                            "ref",
                            NULL))))
            private$..shape <- jmvcore::OptionArray$new(
                "shape",
                shape,
                hidden=TRUE,
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "shape",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionString$new(
                            "shape",
                            NULL))))
            private$..multiplier <- jmvcore::OptionArray$new(
                "multiplier",
                multiplier,
                hidden=TRUE,
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "multiplier",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionString$new(
                            "k",
                            NULL))))
            private$..conf_level <- jmvcore::OptionNumber$new(
                "conf_level",
                conf_level,
                min=0.5,
                max=0.9999999999,
                default=0.95)
            private$..ci_method <- jmvcore::OptionList$new(
                "ci_method",
                ci_method,
                options=list(
                    "wald",
                    "profile"),
                default="wald")
            private$..stars <- jmvcore::OptionBool$new(
                "stars",
                stars,
                default=TRUE)
            private$..color <- jmvcore::OptionList$new(
                "color",
                color,
                options=list(
                    "measure",
                    "adjustment",
                    "between_groups",
                    "no"),
                default="measure")
            private$..color_signif <- jmvcore::OptionList$new(
                "color_signif",
                color_signif,
                options=list(
                    "ignore",
                    "grey_non_signif",
                    "guaranteed_effect"),
                default="grey_non_signif")
            private$..display <- jmvcore::OptionList$new(
                "display",
                display,
                options=list(
                    "auto",
                    "est",
                    "ci",
                    "est_ci",
                    "est_coef",
                    "base",
                    "est_base",
                    "base_est",
                    "base_est_mdiff",
                    "base_est_mratio"),
                default="auto")
            private$..n <- jmvcore::OptionList$new(
                "n",
                n,
                options=list(
                    "range",
                    "min",
                    "no"),
                default="range")
            private$..digits <- jmvcore::OptionList$new(
                "digits",
                digits,
                options=list(
                    "0",
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6"),
                default="0")
            private$..cleannames <- jmvcore::OptionBool$new(
                "cleannames",
                cleannames,
                default=TRUE)
            private$..subtext <- jmvcore::OptionString$new(
                "subtext",
                subtext,
                default="",
                hidden=TRUE)
            private$..tab_theme <- jmvcore::OptionList$new(
                "tab_theme",
                tab_theme,
                options=list(
                    "light",
                    "print_ready"),
                default="light")
            private$..wrap_rows <- jmvcore::OptionNumber$new(
                "wrap_rows",
                wrap_rows,
                min=0,
                default=35)
            private$..wrap_cols <- jmvcore::OptionNumber$new(
                "wrap_cols",
                wrap_cols,
                min=0,
                default=15)
            private$..export_format <- jmvcore::OptionList$new(
                "export_format",
                export_format,
                options=list(
                    "excel",
                    "html",
                    "md"),
                default="excel")
            private$..exportExcel <- jmvcore::OptionAction$new(
                "exportExcel",
                exportExcel)
            private$..export_dir <- jmvcore::OptionString$new(
                "export_dir",
                export_dir,
                default="~/Documents")
            private$..export_filename <- jmvcore::OptionString$new(
                "export_filename",
                export_filename,
                default="Reg_model")
            private$..resetPath <- jmvcore::OptionAction$new(
                "resetPath",
                resetPath)
            private$..xl_check <- jmvcore::OptionBool$new(
                "xl_check",
                xl_check,
                default=FALSE)
            private$..xl_replace <- jmvcore::OptionBool$new(
                "xl_replace",
                xl_replace,
                default=FALSE)

            self$.addOption(private$..outcome)
            self$.addOption(private$..predictors)
            self$.addOption(private$..tab_vars)
            self$.addOption(private$..wt)
            self$.addOption(private$..family)
            self$.addOption(private$..link)
            self$.addOption(private$..outcome_level)
            self$.addOption(private$..trials)
            self$.addOption(private$..effect)
            self$.addOption(private$..measure)
            self$.addOption(private$..empirical)
            self$.addOption(private$..models)
            self$.addOption(private$..na)
            self$.addOption(private$..run_compare)
            self$.addOption(private$..levels_order)
            self$.addOption(private$..levels_collapse)
            self$.addOption(private$..crosses)
            self$.addOption(private$..ref_levels)
            self$.addOption(private$..shape)
            self$.addOption(private$..multiplier)
            self$.addOption(private$..conf_level)
            self$.addOption(private$..ci_method)
            self$.addOption(private$..stars)
            self$.addOption(private$..color)
            self$.addOption(private$..color_signif)
            self$.addOption(private$..display)
            self$.addOption(private$..n)
            self$.addOption(private$..digits)
            self$.addOption(private$..cleannames)
            self$.addOption(private$..subtext)
            self$.addOption(private$..tab_theme)
            self$.addOption(private$..wrap_rows)
            self$.addOption(private$..wrap_cols)
            self$.addOption(private$..export_format)
            self$.addOption(private$..exportExcel)
            self$.addOption(private$..export_dir)
            self$.addOption(private$..export_filename)
            self$.addOption(private$..resetPath)
            self$.addOption(private$..xl_check)
            self$.addOption(private$..xl_replace)
        }),
    active = list(
        outcome = function() private$..outcome$value,
        predictors = function() private$..predictors$value,
        tab_vars = function() private$..tab_vars$value,
        wt = function() private$..wt$value,
        family = function() private$..family$value,
        link = function() private$..link$value,
        outcome_level = function() private$..outcome_level$value,
        trials = function() private$..trials$value,
        effect = function() private$..effect$value,
        measure = function() private$..measure$value,
        empirical = function() private$..empirical$value,
        models = function() private$..models$value,
        na = function() private$..na$value,
        run_compare = function() private$..run_compare$value,
        levels_order = function() private$..levels_order$value,
        levels_collapse = function() private$..levels_collapse$value,
        crosses = function() private$..crosses$value,
        ref_levels = function() private$..ref_levels$value,
        shape = function() private$..shape$value,
        multiplier = function() private$..multiplier$value,
        conf_level = function() private$..conf_level$value,
        ci_method = function() private$..ci_method$value,
        stars = function() private$..stars$value,
        color = function() private$..color$value,
        color_signif = function() private$..color_signif$value,
        display = function() private$..display$value,
        n = function() private$..n$value,
        digits = function() private$..digits$value,
        cleannames = function() private$..cleannames$value,
        subtext = function() private$..subtext$value,
        tab_theme = function() private$..tab_theme$value,
        wrap_rows = function() private$..wrap_rows$value,
        wrap_cols = function() private$..wrap_cols$value,
        export_format = function() private$..export_format$value,
        exportExcel = function() private$..exportExcel$value,
        export_dir = function() private$..export_dir$value,
        export_filename = function() private$..export_filename$value,
        resetPath = function() private$..resetPath$value,
        xl_check = function() private$..xl_check$value,
        xl_replace = function() private$..xl_replace$value),
    private = list(
        ..outcome = NA,
        ..predictors = NA,
        ..tab_vars = NA,
        ..wt = NA,
        ..family = NA,
        ..link = NA,
        ..outcome_level = NA,
        ..trials = NA,
        ..effect = NA,
        ..measure = NA,
        ..empirical = NA,
        ..models = NA,
        ..na = NA,
        ..run_compare = NA,
        ..levels_order = NA,
        ..levels_collapse = NA,
        ..crosses = NA,
        ..ref_levels = NA,
        ..shape = NA,
        ..multiplier = NA,
        ..conf_level = NA,
        ..ci_method = NA,
        ..stars = NA,
        ..color = NA,
        ..color_signif = NA,
        ..display = NA,
        ..n = NA,
        ..digits = NA,
        ..cleannames = NA,
        ..subtext = NA,
        ..tab_theme = NA,
        ..wrap_rows = NA,
        ..wrap_cols = NA,
        ..export_format = NA,
        ..exportExcel = NA,
        ..export_dir = NA,
        ..export_filename = NA,
        ..resetPath = NA,
        ..xl_check = NA,
        ..xl_replace = NA)
)

jmvtabregResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jmvtabregResults",
    inherit = jmvcore::Group,
    active = list(
        html_table = function() private$.items[["html_table"]],
        cache_state = function() private$.items[["cache_state"]],
        compare_state = function() private$.items[["compare_state"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Regression models")
            self$add(jmvcore::Html$new(
                options=options,
                name="html_table",
                title="Table"))
            self$add(jmvcore::Image$new(
                options=options,
                name="cache_state",
                title="",
                width=1080,
                height=1,
                renderFun=".plot",
                visible=FALSE,
                clearWith=list()))
            self$add(jmvcore::Image$new(
                options=options,
                name="compare_state",
                title="",
                width=1080,
                height=1,
                renderFun=".plot",
                visible=FALSE,
                clearWith=list()))}))

jmvtabregBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jmvtabregBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "tabxplor",
                name = "jmvtabreg",
                version = c(1,0,0),
                options = options,
                results = jmvtabregResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'full')
        }))

#' Regressions
#'
#' 
#' @param data A data.frame.
#' @param outcome The outcome variable(s). One model is built per outcome. Set
#'   each outcome's family (and, for a binomial outcome, its modelled level or
#'   number of trials) in the Model table.
#' @param predictors The explanatory variables of the model. Factors are shown
#'   one line per level (the reference level as the neutral value); numeric
#'   predictors as a single line.
#' @param tab_vars A grouping variable. The same model is fitted within each
#'   of its levels and the tables are stacked (like tab_vars for crosstables).
#' @param wt A survey weight variable. Switches to design-based estimation
#'   (scale-invariant sandwich standard errors). Leave empty for unweighted
#'   results.
#' @param family .
#' @param link WHICH MEASURE THE MODEL ESTIMATES -- the only argument that
#'   changes the model. A link IS  a measure, so it takes the same words as
#'   \code{measure}. Chosen per outcome, in the  Model table beside
#'   \code{family}: \code{"auto"} is the family's own (a logistic  regression
#'   for a binary outcome, a linear one for a quantity, a Poisson one for a
#'   count), and \code{"odds_ratio"} / \code{"ratio"} / \code{"difference"} name
#'   the model  whose coefficient IS that measure -- on a binary outcome, the
#'   logistic fit, the modified  Poisson (Zou 2004) and the identity-link
#'   additive-risk one. The picker only ever offers  the links the chosen family
#'   can be fitted on.
#' @param outcome_level .
#' @param trials .
#' @param effect WHERE THE NUMBER COMES FROM, once the model and the reported
#'   measure are fixed.  \itemize{   \item \code{"auto"}: the coefficients when
#'   the reported measure IS the model's own,   the model's predictions
#'   otherwise. Nobody needs to change this.   \item \code{"conditional"}: read
#'   off the model's own coefficients.   \item \code{"marginal"}: worked out
#'   from the model's predictions for every observed   person, then averaged.
#'   \item \code{"at_reference"}: the same, at one profile (every other
#'   predictor at its   reference level / mean).  }
#' @param measure WHICH MEASURE IS REPORTED. It never changes the model: where
#'   it is not the measure the  model estimates (see \code{link}), it is worked
#'   out from the model's predictions.  \itemize{   \item \code{"auto"}: the
#'   model's own measure -- follow from the left. On a prediction   route it
#'   steps back to the outcome's own (a percentage reads as "x times as
#'   likely"),   because a marginal odds ratio is a specialist quantity, asked
#'   for by name.   \item \code{"odds_ratio"} / \code{"ratio"} /
#'   \code{"difference"}: the named measure,   when the outcome's level can
#'   carry it. One it cannot says so, and lists what it does   offer.   \item
#'   \code{"raw_coefficient"}: the model's own coefficient, un-transformed ---
#'   the log   of the reported measure wherever that measure is multiplicative,
#'   and the additive   estimate itself on a model that is already additive.  }
#' @param empirical Show the crude, unadjusted, single-predictor effect beside
#'   each model effect --- the bivariate association that IS the modelised
#'   quantity when there is a single predictor, so the gap between the two is
#'   what adjustment changed.
#' @param models .
#' @param na "drop_by_outcome" (default) fits every model OF ONE OUTCOME on
#'   the same complete cases, which is what makes the observed columns
#'   comparable to the model beside them and lets the likelihood-ratio
#'   comparison run; "drop_by_model" gives each model its own complete cases (a
#'   model on a different population then gets no observed effect); "drop_all"
#'   shares one population across every outcome as well.
#' @param run_compare .
#' @param levels_order .
#' @param levels_collapse .
#' @param crosses .
#' @param ref_levels .
#' @param shape .
#' @param multiplier .
#' @param conf_level The confidence level for intervals and the significance
#'   stars.
#' @param ci_method Wald intervals (also the only option for weighted models)
#'   or profile-likelihood intervals (unweighted binomial / poisson only; needs
#'   MASS). A profile interval is an output of the likelihood at one confidence
#'   level, so it cannot be cached: every change refits the models.
#' @param stars Show per-cell significance stars (the colours read the
#'   confidence interval either way).
#' @param color WHAT the effect cells are coloured by. The colour LADDER
#'   always comes from what the  column estimates (an odds ratio is read on the
#'   odds-ratio scale, a beta on the  standardized-difference one), so what is
#'   left to choose is what the estimate is compared  TO.  \itemize{   \item
#'   \code{"measure"}: the effect's own size (compared to no effect).   \item
#'   \code{"no"}: no colours.   \item \code{"adjustment"}: how far the ADJUSTED
#'   effect moved from the crude one --   needs \code{empirical}.   \item
#'   \code{"between_groups"}: how far each group's effect is from the first
#'   group's   -- needs \code{tab_vars}.  }
#' @param color_signif How significance interacts with the colours: observed
#'   size + grey out non-significant cells, colour only the guaranteed
#'   (error-adjusted) effect, ignore significance.
#' @param display The estimate-cell LAYOUT (never the estimand: a display may
#'   fold in another quantity of the SAME fit, it can never change the fit). The
#'   same named layouts \code{tab()} offers, written in the same \code{\{\}}
#'   grammar: \code{est} is whatever the column estimates and \code{base} the
#'   level it sits on (an adjusted probability, an adjusted mean). \code{"auto"}
#'   keeps the built-in layout.
#' @param n The column giving the number of observations behind each predictor
#'   level: \code{"range"} prints \code{min-max} when several models were fitted
#'   on different people, \code{"min"} the smallest count only, \code{"no"} no
#'   column at all.
#' @param digits The minimum number of digits to print, as a single integer
#'   (0-6): each measure keeps its  own precision where that is finer (an odds
#'   ratio reads at two decimals, a mean score at  one). In R, \code{tab_reg()}
#'   also names one display field at a time,  \code{digits = c(ratio = 3)}.
#' @param cleannames Strip numeric prefixes from factor level labels.
#' @param subtext A free note printed below the table.
#' @param tab_theme How the table is painted, in the results panel and in
#'   every export.  \code{"light"} is the colour palette; \code{"print_ready"}
#'   says the same thing  typographically --- bold, italics, underlines and
#'   marks instead of blue and red ---  for a page that has no colour. See
#'   \code{\link{tab_css}}.
#' @param wrap_rows .
#' @param wrap_cols .
#' @param export_format .
#' @param exportExcel Press to export the table to the chosen format (the
#'   button label follows the format).
#' @param export_dir The folder to save the exported file in. Blank or
#'   \code{~/Documents} auto-detects your real Documents folder (a redirected
#'   \code{D:/Documents} or network Documents included). Type any other folder
#'   to override; a leading \code{~} there expands to your home folder.
#' @param export_filename The bare file name, with NO extension (the chosen
#'   format adds it).
#' @param resetPath Reset the folder and file name to their defaults (your
#'   Documents folder and "Regression").
#' @param xl_check Excel export only: draw the model-check plots
#'   (\code{reg_check_plots()}) under each table in the workbook --- the panels
#'   that apply to the fitted family (\code{tab_xl(check = "auto")}). Needs
#'   \code{ggplot2} and \code{gridExtra}; without them the export says so and
#'   writes the table alone.
#' @param xl_replace "Set to \code{TRUE} to overwrite an existing file."
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$html_table} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$cache_state} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$compare_state} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
jmvtabreg <- function(
    data,
    outcome = NULL,
    predictors = NULL,
    tab_vars = NULL,
    wt = NULL,
    family = NULL,
    link = NULL,
    outcome_level = NULL,
    trials = NULL,
    effect = "auto",
    measure = "auto",
    empirical = TRUE,
    models = NULL,
    na = "drop_by_outcome",
    run_compare = FALSE,
    levels_order = NULL,
    levels_collapse = NULL,
    crosses = NULL,
    ref_levels = NULL,
    shape = NULL,
    multiplier = NULL,
    conf_level = 0.95,
    ci_method = "wald",
    stars = TRUE,
    color = "measure",
    color_signif = "grey_non_signif",
    display = "auto",
    n = "range",
    digits = "0",
    cleannames = TRUE,
    subtext = "",
    tab_theme = "light",
    wrap_rows = 35,
    wrap_cols = 15,
    export_format = "excel",
    exportExcel = FALSE,
    export_dir = "~/Documents",
    export_filename = "Reg_model",
    resetPath = FALSE,
    xl_check = FALSE,
    xl_replace = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jmvtabreg requires jmvcore to be installed (restart may be required)")

    if ( ! missing(outcome)) outcome <- jmvcore::resolveQuo(jmvcore::enquo(outcome))
    if ( ! missing(predictors)) predictors <- jmvcore::resolveQuo(jmvcore::enquo(predictors))
    if ( ! missing(tab_vars)) tab_vars <- jmvcore::resolveQuo(jmvcore::enquo(tab_vars))
    if ( ! missing(wt)) wt <- jmvcore::resolveQuo(jmvcore::enquo(wt))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(outcome), outcome, NULL),
            `if`( ! missing(predictors), predictors, NULL),
            `if`( ! missing(tab_vars), tab_vars, NULL),
            `if`( ! missing(wt), wt, NULL))

    for (v in tab_vars) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- jmvtabregOptions$new(
        outcome = outcome,
        predictors = predictors,
        tab_vars = tab_vars,
        wt = wt,
        family = family,
        link = link,
        outcome_level = outcome_level,
        trials = trials,
        effect = effect,
        measure = measure,
        empirical = empirical,
        models = models,
        na = na,
        run_compare = run_compare,
        levels_order = levels_order,
        levels_collapse = levels_collapse,
        crosses = crosses,
        ref_levels = ref_levels,
        shape = shape,
        multiplier = multiplier,
        conf_level = conf_level,
        ci_method = ci_method,
        stars = stars,
        color = color,
        color_signif = color_signif,
        display = display,
        n = n,
        digits = digits,
        cleannames = cleannames,
        subtext = subtext,
        tab_theme = tab_theme,
        wrap_rows = wrap_rows,
        wrap_cols = wrap_cols,
        export_format = export_format,
        exportExcel = exportExcel,
        export_dir = export_dir,
        export_filename = export_filename,
        resetPath = resetPath,
        xl_check = xl_check,
        xl_replace = xl_replace)

    analysis <- jmvtabregClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

