
# This file is automatically generated, you probably don't want to edit this

jmvtabOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jmvtabOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            row_vars = NULL,
            col_vars = NULL,
            tab_vars = NULL,
            wt = NULL,
            pct = "no",
            color = "no",
            color_signif = "ignore",
            test = FALSE,
            anova = "welch",
            na = "keep",
            lvs = "all",
            cleannames = TRUE,
            ref_levels = NULL,
            levels_order = NULL,
            levels_collapse = NULL,
            shape = NULL,
            ref = "auto",
            ref2 = "first",
            comp = "tab",
            ci = "auto",
            conf_level = 0.95,
            stars = FALSE,
            design_effect = FALSE,
            ci_method_cell = "wilson",
            ci_method_diff = "newcombe",
            ci_method_mean_diff = "welch",
            ci_method_mean_ratio = "robust",
            tab_theme = "light",
            totaltab = "line",
            wrap_rows = 35,
            wrap_cols = 15,
            display = "auto",
            n = "range",
            add_pct = FALSE,
            subtext = "",
            digits = "0",
            n_min = 0,
            export_format = "excel",
            exportExcel = FALSE,
            export_dir = "~/Documents",
            export_filename = "Table",
            resetPath = FALSE,
            xl_replace = FALSE, ...) {

            super$initialize(
                package="tabxplor",
                name="jmvtab",
                requiresData=TRUE,
                ...)

            private$..row_vars <- jmvcore::OptionVariables$new(
                "row_vars",
                row_vars,
                permitted=list(
                    "numeric",
                    "factor"),
                default=NULL,
                suggested=list(
                    "nominal",
                    "ordinal"))
            private$..col_vars <- jmvcore::OptionVariables$new(
                "col_vars",
                col_vars,
                suggested=list(
                    "nominal",
                    "ordinal",
                    "continuous"),
                permitted=list(
                    "numeric",
                    "factor"),
                default=NULL)
            private$..tab_vars <- jmvcore::OptionVariables$new(
                "tab_vars",
                tab_vars,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..wt <- jmvcore::OptionVariable$new(
                "wt",
                wt,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..pct <- jmvcore::OptionList$new(
                "pct",
                pct,
                options=list(
                    "no",
                    "row",
                    "col",
                    "all",
                    "all_tabs"),
                default="no")
            private$..color <- jmvcore::OptionList$new(
                "color",
                color,
                options=list(
                    "no",
                    "auto",
                    "difference",
                    "ratio",
                    "odds_ratio",
                    "contrib"),
                default="no")
            private$..color_signif <- jmvcore::OptionList$new(
                "color_signif",
                color_signif,
                options=list(
                    "ignore",
                    "grey_non_signif",
                    "guaranteed_effect"),
                default="ignore")
            private$..test <- jmvcore::OptionBool$new(
                "test",
                test,
                default=FALSE)
            private$..anova <- jmvcore::OptionList$new(
                "anova",
                anova,
                options=list(
                    "welch",
                    "classic"),
                default="welch")
            private$..na <- jmvcore::OptionList$new(
                "na",
                na,
                options=list(
                    "keep",
                    "drop",
                    "drop_all",
                    "common_base"),
                default="keep")
            private$..lvs <- jmvcore::OptionList$new(
                "lvs",
                lvs,
                options=list(
                    "all",
                    "first",
                    "auto"),
                default="all")
            private$..cleannames <- jmvcore::OptionBool$new(
                "cleannames",
                cleannames,
                default=TRUE)
            private$..ref_levels <- jmvcore::OptionArray$new(
                "ref_levels",
                ref_levels,
                hidden=TRUE,
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "ref_levels",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionString$new(
                            "ref",
                            NULL))))
            private$..levels_order <- jmvcore::OptionArray$new(
                "levels_order",
                levels_order,
                hidden=TRUE,
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "levels_order",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionArray$new(
                            "levels",
                            NULL,
                            template=jmvcore::OptionString$new(
                                "levels",
                                NULL)))))
            private$..levels_collapse <- jmvcore::OptionArray$new(
                "levels_collapse",
                levels_collapse,
                hidden=TRUE,
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "levels_collapse",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionString$new(
                            "label",
                            NULL),
                        jmvcore::OptionArray$new(
                            "levels",
                            NULL,
                            template=jmvcore::OptionString$new(
                                "levels",
                                NULL)))))
            private$..shape <- jmvcore::OptionArray$new(
                "shape",
                shape,
                hidden=TRUE,
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "shape",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionString$new(
                            "shape",
                            NULL))))
            private$..ref <- jmvcore::OptionString$new(
                "ref",
                ref,
                default="auto",
                hidden=TRUE)
            private$..ref2 <- jmvcore::OptionString$new(
                "ref2",
                ref2,
                default="first",
                hidden=TRUE)
            private$..comp <- jmvcore::OptionList$new(
                "comp",
                comp,
                options=list(
                    "tab",
                    "all"),
                default="tab")
            private$..ci <- jmvcore::OptionList$new(
                "ci",
                ci,
                options=list(
                    "auto",
                    "no",
                    "cell",
                    "ref"),
                default="auto")
            private$..conf_level <- jmvcore::OptionNumber$new(
                "conf_level",
                conf_level,
                min=0,
                max=1,
                default=0.95)
            private$..stars <- jmvcore::OptionBool$new(
                "stars",
                stars,
                default=FALSE)
            private$..design_effect <- jmvcore::OptionBool$new(
                "design_effect",
                design_effect,
                default=FALSE)
            private$..ci_method_cell <- jmvcore::OptionList$new(
                "ci_method_cell",
                ci_method_cell,
                options=list(
                    "wilson",
                    "wald",
                    "beta"),
                default="wilson")
            private$..ci_method_diff <- jmvcore::OptionList$new(
                "ci_method_diff",
                ci_method_diff,
                options=list(
                    "newcombe",
                    "ac",
                    "wald"),
                default="newcombe")
            private$..ci_method_mean_diff <- jmvcore::OptionList$new(
                "ci_method_mean_diff",
                ci_method_mean_diff,
                options=list(
                    "welch",
                    "student",
                    "ols"),
                default="welch")
            private$..ci_method_mean_ratio <- jmvcore::OptionList$new(
                "ci_method_mean_ratio",
                ci_method_mean_ratio,
                options=list(
                    "robust",
                    "quasipoisson",
                    "poisson"),
                default="robust")
            private$..tab_theme <- jmvcore::OptionList$new(
                "tab_theme",
                tab_theme,
                options=list(
                    "light",
                    "print_ready"),
                default="light")
            private$..totaltab <- jmvcore::OptionList$new(
                "totaltab",
                totaltab,
                options=list(
                    "line",
                    "table",
                    "no"),
                default="line")
            private$..wrap_rows <- jmvcore::OptionNumber$new(
                "wrap_rows",
                wrap_rows,
                min=0,
                default=35)
            private$..wrap_cols <- jmvcore::OptionNumber$new(
                "wrap_cols",
                wrap_cols,
                min=0,
                default=15)
            private$..display <- jmvcore::OptionList$new(
                "display",
                display,
                options=list(
                    "auto",
                    "base",
                    "base_ci",
                    "ci",
                    "diff",
                    "ratio",
                    "or",
                    "base_diff",
                    "base_ratio",
                    "or_base",
                    "base_or",
                    "n",
                    "wn",
                    "pct",
                    "mean",
                    "mean_sd",
                    "mean_cv",
                    "ctr",
                    "var"),
                default="auto")
            private$..n <- jmvcore::OptionList$new(
                "n",
                n,
                options=list(
                    "range",
                    "min",
                    "no"),
                default="range")
            private$..add_pct <- jmvcore::OptionBool$new(
                "add_pct",
                add_pct,
                default=FALSE)
            private$..subtext <- jmvcore::OptionString$new(
                "subtext",
                subtext,
                default="",
                hidden=TRUE)
            private$..digits <- jmvcore::OptionList$new(
                "digits",
                digits,
                options=list(
                    "0",
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6"),
                default="0")
            private$..n_min <- jmvcore::OptionInteger$new(
                "n_min",
                n_min,
                min=0,
                default=0)
            private$..export_format <- jmvcore::OptionList$new(
                "export_format",
                export_format,
                options=list(
                    "excel",
                    "html",
                    "md"),
                default="excel")
            private$..exportExcel <- jmvcore::OptionAction$new(
                "exportExcel",
                exportExcel)
            private$..export_dir <- jmvcore::OptionString$new(
                "export_dir",
                export_dir,
                default="~/Documents")
            private$..export_filename <- jmvcore::OptionString$new(
                "export_filename",
                export_filename,
                default="Table")
            private$..resetPath <- jmvcore::OptionAction$new(
                "resetPath",
                resetPath)
            private$..xl_replace <- jmvcore::OptionBool$new(
                "xl_replace",
                xl_replace,
                default=FALSE)

            self$.addOption(private$..row_vars)
            self$.addOption(private$..col_vars)
            self$.addOption(private$..tab_vars)
            self$.addOption(private$..wt)
            self$.addOption(private$..pct)
            self$.addOption(private$..color)
            self$.addOption(private$..color_signif)
            self$.addOption(private$..test)
            self$.addOption(private$..anova)
            self$.addOption(private$..na)
            self$.addOption(private$..lvs)
            self$.addOption(private$..cleannames)
            self$.addOption(private$..ref_levels)
            self$.addOption(private$..levels_order)
            self$.addOption(private$..levels_collapse)
            self$.addOption(private$..shape)
            self$.addOption(private$..ref)
            self$.addOption(private$..ref2)
            self$.addOption(private$..comp)
            self$.addOption(private$..ci)
            self$.addOption(private$..conf_level)
            self$.addOption(private$..stars)
            self$.addOption(private$..design_effect)
            self$.addOption(private$..ci_method_cell)
            self$.addOption(private$..ci_method_diff)
            self$.addOption(private$..ci_method_mean_diff)
            self$.addOption(private$..ci_method_mean_ratio)
            self$.addOption(private$..tab_theme)
            self$.addOption(private$..totaltab)
            self$.addOption(private$..wrap_rows)
            self$.addOption(private$..wrap_cols)
            self$.addOption(private$..display)
            self$.addOption(private$..n)
            self$.addOption(private$..add_pct)
            self$.addOption(private$..subtext)
            self$.addOption(private$..digits)
            self$.addOption(private$..n_min)
            self$.addOption(private$..export_format)
            self$.addOption(private$..exportExcel)
            self$.addOption(private$..export_dir)
            self$.addOption(private$..export_filename)
            self$.addOption(private$..resetPath)
            self$.addOption(private$..xl_replace)
        }),
    active = list(
        row_vars = function() private$..row_vars$value,
        col_vars = function() private$..col_vars$value,
        tab_vars = function() private$..tab_vars$value,
        wt = function() private$..wt$value,
        pct = function() private$..pct$value,
        color = function() private$..color$value,
        color_signif = function() private$..color_signif$value,
        test = function() private$..test$value,
        anova = function() private$..anova$value,
        na = function() private$..na$value,
        lvs = function() private$..lvs$value,
        cleannames = function() private$..cleannames$value,
        ref_levels = function() private$..ref_levels$value,
        levels_order = function() private$..levels_order$value,
        levels_collapse = function() private$..levels_collapse$value,
        shape = function() private$..shape$value,
        ref = function() private$..ref$value,
        ref2 = function() private$..ref2$value,
        comp = function() private$..comp$value,
        ci = function() private$..ci$value,
        conf_level = function() private$..conf_level$value,
        stars = function() private$..stars$value,
        design_effect = function() private$..design_effect$value,
        ci_method_cell = function() private$..ci_method_cell$value,
        ci_method_diff = function() private$..ci_method_diff$value,
        ci_method_mean_diff = function() private$..ci_method_mean_diff$value,
        ci_method_mean_ratio = function() private$..ci_method_mean_ratio$value,
        tab_theme = function() private$..tab_theme$value,
        totaltab = function() private$..totaltab$value,
        wrap_rows = function() private$..wrap_rows$value,
        wrap_cols = function() private$..wrap_cols$value,
        display = function() private$..display$value,
        n = function() private$..n$value,
        add_pct = function() private$..add_pct$value,
        subtext = function() private$..subtext$value,
        digits = function() private$..digits$value,
        n_min = function() private$..n_min$value,
        export_format = function() private$..export_format$value,
        exportExcel = function() private$..exportExcel$value,
        export_dir = function() private$..export_dir$value,
        export_filename = function() private$..export_filename$value,
        resetPath = function() private$..resetPath$value,
        xl_replace = function() private$..xl_replace$value),
    private = list(
        ..row_vars = NA,
        ..col_vars = NA,
        ..tab_vars = NA,
        ..wt = NA,
        ..pct = NA,
        ..color = NA,
        ..color_signif = NA,
        ..test = NA,
        ..anova = NA,
        ..na = NA,
        ..lvs = NA,
        ..cleannames = NA,
        ..ref_levels = NA,
        ..levels_order = NA,
        ..levels_collapse = NA,
        ..shape = NA,
        ..ref = NA,
        ..ref2 = NA,
        ..comp = NA,
        ..ci = NA,
        ..conf_level = NA,
        ..stars = NA,
        ..design_effect = NA,
        ..ci_method_cell = NA,
        ..ci_method_diff = NA,
        ..ci_method_mean_diff = NA,
        ..ci_method_mean_ratio = NA,
        ..tab_theme = NA,
        ..totaltab = NA,
        ..wrap_rows = NA,
        ..wrap_cols = NA,
        ..display = NA,
        ..n = NA,
        ..add_pct = NA,
        ..subtext = NA,
        ..digits = NA,
        ..n_min = NA,
        ..export_format = NA,
        ..exportExcel = NA,
        ..export_dir = NA,
        ..export_filename = NA,
        ..resetPath = NA,
        ..xl_replace = NA)
)

jmvtabResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jmvtabResults",
    inherit = jmvcore::Group,
    active = list(
        html_table = function() private$.items[["html_table"]],
        cache_state = function() private$.items[["cache_state"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Crosstables")
            self$add(jmvcore::Html$new(
                options=options,
                name="html_table",
                title="Table"))
            self$add(jmvcore::Image$new(
                options=options,
                name="cache_state",
                title="",
                width=1080,
                height=1,
                renderFun=".plot",
                visible=FALSE,
                clearWith=list()))}))

jmvtabBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jmvtabBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "tabxplor",
                name = "jmvtab",
                version = c(1,0,0),
                options = options,
                results = jmvtabResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'full')
        }))

#' Crosstables
#'
#' 
#' @param data A data.frame.
#' @param row_vars The row variable, which will be printed with one level per
#'   line. If numeric, it will be converted to factor. If several row variables
#'   are provided, it's not possible to add any tab_vars.
#' @param col_vars One column is printed for each level of each column
#'   variable. For numeric variables means are calculated, in a single column.
#' @param tab_vars One subtable is made for each combination of levels of the
#'   tab variables. All tab variables are converted to factor. Leave empty to
#'   make a simple table. Not used when there are several row_vars.
#' @param wt A weight variable, of class numeric. Leave empty for unweighted
#'   results.
#' @param pct The type of percentages to calculate :  \itemize{    \item
#'   \code{"row"}: row percentages.    \item \code{"col"}: column percentages.
#'   \item \code{"all"}: frequencies for each subtable/group, if there is
#'   \code{tab_vars}.    \item \code{"all_tabs"}: frequencies for the whole (set
#'   of) table(s).  }
#' @param color Which measure to use for color helpers, as a single string.
#'   The values are the measure  names \code{tab()} itself takes (the short
#'   spellings \code{"diff"} / \code{"OR"} stay  valid aliases in R).  \itemize{
#'   \item \code{"no"}: by default, no colors are printed.    \item
#'   \code{"auto"}: a smart per-column-type default (percentage-point difference
#'   on    the text plus a relative-risk highlight on the background for
#'   factors, mean ratio for    numeric columns).    \item \code{"difference"}:
#'   color the difference of each cell from its total (or    reference cell).
#'   For factors this is a percentage-point difference; for numeric columns
#'   the standardized (SD-scaled) mean difference.    \item \code{"ratio"}:
#'   color the relative risk (factors) or mean ratio (numeric).    \item
#'   \code{"odds_ratio"}: for \code{pct == "col"} or \code{pct == "row"}, color
#'   based on odds    ratios. To PRINT them, set \code{display} (the colour and
#'   the printed quantity are two    questions).    \item \code{"contrib"}:
#'   color cells based on their contribution to variance    (factor columns
#'   only).  } How significance gates these colors is set separately by
#'   \code{color_signif}.
#' @param color_signif How statistical significance gates the colors, as a
#'   single string.  \itemize{    \item \code{"ignore"}: by default, color every
#'   deviation by its observed size.    \item \code{"grey_non_signif"}: color by
#'   observed size, but grey out cells whose    deviation is not significant (at
#'   \code{conf_level}). A confidence interval on the    difference is computed
#'   automatically.    \item \code{"guaranteed_effect"}: color by the guaranteed
#'   (confidence-bound) effect --    all cells whose interval clears the
#'   threshold show, with dimmer colors.  }
#' @param test Set to \code{TRUE} to add a test p-value row: a Chi-square test
#'   for categorical column variables and an ANOVA F-test for numeric ones
#'   (chosen automatically per column type). Also enables colouring cells by
#'   their contribution to variance.
#' @param anova Which F statistic to display for numeric column variables when
#'   the test is on: Welch's F (default, does not assume equal variances) or the
#'   classic pooled F.
#' @param na The policy to adopt with missing values. It must be a single
#'   string.  \itemize{    \item \code{na = "keep"}: by default, prints
#'   \code{NA}'s as explicit \code{"NA"} level.    \item \code{na = "drop"}:
#'   each column variable drops its own \code{NA}'s, so tables    made with
#'   different column variables may have a different number of observations.
#'   \item \code{na = "drop_all"}: drops every observation missing on the row
#'   variable,    any column variable or a tab variable (all columns then share
#'   one base).    \item \code{na = "common_base"}: fixes a single population
#'   (non-missing on the row    variable and the first column variable), while
#'   secondary column variables keep their    own \code{NA}'s. Reproduces the
#'   historical \code{tab()} behaviour.    }
#' @param lvs The levels of \code{col_vars} to keep.  \itemize{    \item
#'   \code{"all"}: by default, all levels are kept.    \item \code{"first"}:
#'   only keep the first level of each \code{col_vars}    \item \code{"auto"}:
#'   keep the first level when \code{col_var} is only two levels,    keep all
#'   levels otherwise.    }
#' @param cleannames By default, clean levels names, by removing prefix
#'   numbers like "1-", and text in parenthesis. Set to \code{FALSE} to avoid
#'   this behaviour.
#' @param ref_levels .
#' @param levels_order .
#' @param levels_collapse .
#' @param shape .
#' @param ref The reference cell to calculate differences and ratios   (used
#'   to print \code{colors}) :   \itemize{    \item \code{"auto"}: by default,
#'   cell difference from the corresponding total    (rows or cols depending on
#'   \code{pct = "row"} or \code{pct = "col"}) is    used for \code{diff} ; cell
#'   ratio from the first line (or col) is use for \code{OR}    (odds
#'   ratio/relative risks ratio).    \item \code{"tot"}: totals are always used.
#'   \item \code{"first"}: calculate cell difference or ratio from the first
#'   cell  of the row or column (useful to color temporal developments).
#'   \item \code{n}: when \code{ref} is an integer, the nth row (or column) is
#'   used for comparison.    \item \code{"regex"}: when \code{ref} is a string,
#'   it it used as a regular expression,    to match with the names of the rows
#'   (or columns). Be precise enough to match only one    column or row,
#'   otherwise you get a warning message.    \item \code{"no"}: not use ref and
#'   not calculate diffs to gain calculation time.  }
#' @param ref2 With \code{OR = OR} (odds-ratios) and a 3+ levels factor, a
#'   second reference cell  is needed to calculate relative risks ratios. First
#'   cell by default.
#' @param comp The comparison level : by subtables/groups, or for the whole
#'   table.
#' @param ci \strong{What the confidence interval is anchored on} -- one
#'   question, four answers. The  GEOMETRY of the interval is not asked here: it
#'   follows the comparison the table makes  (set by \code{color} /
#'   \code{display}), so a difference table gets a difference  interval and a
#'   ratio table a ratio one.  \itemize{   \item \code{"auto"}: build the
#'   comparison interval when something reads it   (\code{stars}, or a
#'   \code{color_signif} policy), and none otherwise.   \item \code{"no"}: no
#'   interval at all.   \item \code{"cell"}: each cell's own interval (a
#'   percentage / a mean with its own   bounds). It anchors nothing to compare,
#'   so \code{stars} and \code{color_signif} are   informed and switched off.
#'   \item \code{"ref"}: the interval of the comparison with the reference cell
#'   -- what   \code{stars} and \code{color_signif} read.  }
#' @param conf_level The confidence level, a single numeric between 0 and 1
#'   --- 0.95 by default.
#' @param stars With \code{ci = "diff"}, print significance stars (\code{*}
#'   \code{**} \code{***}) for the difference of each cell from its reference.
#'   Read from the same confidence interval that is displayed, so stars and
#'   bracket always agree.
#' @param design_effect For a WEIGHTED table, make the confidence intervals,
#'   the significance stars, the colour thresholds AND the p-values account for
#'   the unequal weighting (the exact flat survey-design variance) instead of
#'   using the raw number of respondents. Sets options(tabxplor.design_effect).
#'   Off by default; it moves every interval in the table, not only the p-value.
#' @param ci_method_cell The proportion confidence-interval method for
#'   \code{ci = "cell"}: \code{"wilson"} (the score interval, default) or
#'   \code{"wald"} (the normal approximation).
#' @param ci_method_diff The proportion confidence-interval method for
#'   \code{ci = "diff"}. \code{"newcombe"} (default) is the dual of the
#'   two-proportion score test, so the interval and the significance stars
#'   always agree.
#' @param ci_method_mean_diff The confidence-interval method for the
#'   difference of numeric means (means with \code{ci = "diff"}): Welch
#'   (default), Student (the two groups pooled) or OLS (pooled over every level
#'   of the variable, i.e. the interval a linear model gives that coefficient).
#' @param ci_method_mean_ratio The confidence-interval method for a ratio of
#'   numeric means (means with \code{ci = "ratio"}).
#' @param tab_theme How the table is painted, in the results panel and in
#'   every export.  \code{"light"} is the colour palette; \code{"print_ready"}
#'   says the same thing  typographically --- bold, italics, underlines and
#'   marks instead of blue and red ---  for a page that has no colour. See
#'   \code{\link{tab_css}}.
#' @param totaltab The total table, if there are subtables/groups   (i.e. when
#'   \code{tab_vars} is provided). Vectorised over \code{row_vars}.  \itemize{
#'   \item \code{"line"}: by default, add a general total line (necessary for
#'   calculations with \code{comp = "all"})    \item \code{"table"}: add a
#'   complete total table   (i.e. \code{row_var} by \code{col_vars} without
#'   \code{tab_vars}).    \item \code{"no"}: not to draw any total table.   }
#' @param wrap_rows By default, rownames are wrapped when larger than 30
#'   characters.
#' @param wrap_cols By default, colnames are wrapped when larger than 12
#'   characters.
#' @param display What each cell shows. Every value here is a
#'   \code{tab(display =)} value: a bare field  name, a named layout such as
#'   \code{"base_ci"} (each value with its interval), or a  \code{\{\}} template
#'   combining fields. \code{"auto"} keeps whatever the table was  built with. A
#'   template naming a field the table does not carry renders empty and says
#'   which argument would fill it.
#' @param n How many people the table is about: \code{"range"} prints the
#'   unweighted base beside the Total cell (as \code{min-max} when the column
#'   variables rest on different people), \code{"min"} the smallest base only,
#'   \code{"no"} no count at all.
#' @param add_pct Set to \code{TRUE} to add a column with the frequencies of
#'   the row variable (for \code{pct = "row"}) or a row with the frequencies of
#'   the column variable (for  \code{pct = "col"})
#' @param subtext A character vector to print rows of legend under the table.
#' @param digits The number of digits to print, as a single integer (0-6). In
#'   R, \code{tab()} also accepts an integer vector the same length as
#'   \code{col_vars}.
#' @param n_min A pure display filter (0 = off). A row is dropped only when
#'   its largest base across the column variables is below \code{n_min};
#'   surviving cells whose own base is below \code{n_min} are blanked. Under
#'   \code{pct = "col"} weak columns are dropped instead. Totals, the added-n
#'   row/column and the p-value line are always kept. Recomputes nothing.
#' @param export_format The export file format: Excel (\code{.xlsx}), HTML
#'   (\code{.html}) or Markdown (\code{.md}).
#' @param exportExcel Press to export the table to the chosen format (the
#'   button label follows the format).
#' @param export_dir The folder to save the exported file in. Blank or
#'   \code{~/Documents} auto-detects your real Documents folder (a redirected
#'   \code{D:/Documents} or network Documents included). Type any other folder
#'   to override; a leading \code{~} there expands to your home folder.
#' @param export_filename The bare file name, with NO extension (the chosen
#'   format adds it). Illegal characters are removed automatically. Blank saves
#'   as "Table".
#' @param resetPath Reset the folder and file name to their defaults (your
#'   Documents folder and "Table").
#' @param xl_replace "Set to \code{TRUE} to overwrite an existing file."
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$html_table} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$cache_state} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
jmvtab <- function(
    data,
    row_vars = NULL,
    col_vars = NULL,
    tab_vars = NULL,
    wt = NULL,
    pct = "no",
    color = "no",
    color_signif = "ignore",
    test = FALSE,
    anova = "welch",
    na = "keep",
    lvs = "all",
    cleannames = TRUE,
    ref_levels = NULL,
    levels_order = NULL,
    levels_collapse = NULL,
    shape = NULL,
    ref = "auto",
    ref2 = "first",
    comp = "tab",
    ci = "auto",
    conf_level = 0.95,
    stars = FALSE,
    design_effect = FALSE,
    ci_method_cell = "wilson",
    ci_method_diff = "newcombe",
    ci_method_mean_diff = "welch",
    ci_method_mean_ratio = "robust",
    tab_theme = "light",
    totaltab = "line",
    wrap_rows = 35,
    wrap_cols = 15,
    display = "auto",
    n = "range",
    add_pct = FALSE,
    subtext = "",
    digits = "0",
    n_min = 0,
    export_format = "excel",
    exportExcel = FALSE,
    export_dir = "~/Documents",
    export_filename = "Table",
    resetPath = FALSE,
    xl_replace = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jmvtab requires jmvcore to be installed (restart may be required)")

    if ( ! missing(row_vars)) row_vars <- jmvcore::resolveQuo(jmvcore::enquo(row_vars))
    if ( ! missing(col_vars)) col_vars <- jmvcore::resolveQuo(jmvcore::enquo(col_vars))
    if ( ! missing(tab_vars)) tab_vars <- jmvcore::resolveQuo(jmvcore::enquo(tab_vars))
    if ( ! missing(wt)) wt <- jmvcore::resolveQuo(jmvcore::enquo(wt))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(row_vars), row_vars, NULL),
            `if`( ! missing(col_vars), col_vars, NULL),
            `if`( ! missing(tab_vars), tab_vars, NULL),
            `if`( ! missing(wt), wt, NULL))

    for (v in tab_vars) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- jmvtabOptions$new(
        row_vars = row_vars,
        col_vars = col_vars,
        tab_vars = tab_vars,
        wt = wt,
        pct = pct,
        color = color,
        color_signif = color_signif,
        test = test,
        anova = anova,
        na = na,
        lvs = lvs,
        cleannames = cleannames,
        ref_levels = ref_levels,
        levels_order = levels_order,
        levels_collapse = levels_collapse,
        shape = shape,
        ref = ref,
        ref2 = ref2,
        comp = comp,
        ci = ci,
        conf_level = conf_level,
        stars = stars,
        design_effect = design_effect,
        ci_method_cell = ci_method_cell,
        ci_method_diff = ci_method_diff,
        ci_method_mean_diff = ci_method_mean_diff,
        ci_method_mean_ratio = ci_method_mean_ratio,
        tab_theme = tab_theme,
        totaltab = totaltab,
        wrap_rows = wrap_rows,
        wrap_cols = wrap_cols,
        display = display,
        n = n,
        add_pct = add_pct,
        subtext = subtext,
        digits = digits,
        n_min = n_min,
        export_format = export_format,
        exportExcel = exportExcel,
        export_dir = export_dir,
        export_filename = export_filename,
        resetPath = resetPath,
        xl_replace = xl_replace)

    analysis <- jmvtabClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

